spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/administrativo_financiero
    username: sisapp
    password: sisapp98
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: OrigamiGT
      max-lifetime: 1800000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  main:
    allow-bean-definition-overriding: true

app:
  documental: C:/archivos/documentos/
  imagenes: C:/archivos/imagenes/
  urlResource: http://127.0.0.1:8713/servicios-archivos/ug/api/

logging:
  level:
    org:
      hibernate:
        sql: debug