spring:
  data:
    mongodb:
      port: 27017
      host: 127.0.0.1
      database: correodb

ugDocs:
  apiContext: http://127.0.0.1:8713/servicios-documental/ug/api/
  imagenes: C:/archivos/imagenes/
  archivos: C:/archivos/documentos/
  rutaReportes: classpath:reportes/
  rutaImagenes: classpath:imagenes/